name: rnaseq-lib3
channels:
- conda-forge
dependencies:
- python=3
- anaconda
- biopython
- jupyter_contrib_nbextensions
- pip:
  - synapseclient
  - annoy
  - holoviews
  - trimap
  - seaborn
  - tqdm
